### ISSUE TITLE
Bugs in Super Long Distances with High Precision Calculations

### ISSUE THREAD

**Issue by AESisverystrong** [AlphaMode/MinecraftLong2#4]
I’ve encountered a number of issues when traveling to super long distances in Minecraft, such as around 1E100, with the Windows Long Path enabled.

At these extreme distances, I’m finding that blocks cannot be placed and entities disappear (with the sole exception being the player character). I can still destroy blocks, but struggling with several other features. For instance, I can’t change the player perspective by pressing F5 - this leads to permanent nonresponsiveness.

Furthermore, I've noticed that in non-superflat worlds, these distances generate an endless sea of lava, without bedrock. This behavior is reminiscent of earlier versions of Minecraft and I suspect it’s related to the map generator.

My questions are: Did you modify the map generator or just enable it to support high precision? What’s the cause of this 'Sea of Lava' bug at extreme distances?

Besides, it seems only the 'tp' and 'teleport' commands have been enhanced to support these super long distances, exceeding 1E100. Other commands seem to be still limited by the original limitations in Minecraft such as 1E8 and hence, are unable to function beyond these limits.

I would greatly appreciate any assistance or insights you could provide on these issues.

Translated by GPT-4.

**Comment by AESisverystrong** [comment]
If these problems are caused by not fully modifying to high precision, **_do you plan to fully modify to high precision?_** (I know it's hard)

Also I've noticed that using this version causes Minecraft to hang indefinitely after being unresponsive without being able to resume running, I'm guessing it's the constant unresponsiveness caused by too many timed tasks (processing one and the next spawns immediately, infinite loops without being able to process graphics threads). **_Would it be possible to add a function that modifies the RTC speed to slow down the whole MC_** and make the MC think the computer is fast, so that this problem shouldn't occur.

Translated with DeepL.com (free version)

**Comment by AlphaMode** [comment]
I plan to address these issue in MinecraftBig 3 which is a rewrite of this project. I don't know if I uploaded it to github or not yet

**Comment by AESisverystrong** [comment]
Thank you very much for your reply! What is the root cause of these problems? Also how is your project related to the [Cursed Creations] project?

**Comment by AlphaMode** [comment]
I'm not aware of any cursed creation project. Most of these issues exist because they haven't been converted to use BigInt/BigDec either because I just haven't gotten to them yet or because it would be to slow. Terrain generation is vanilla, it hasn't been modified to support bigger precision ranges. I think I did have a branch that did that but I think it got deleted.

**Comment by AESisverystrong** [comment]
This project, which contains your project: "https://github.com/4194304/cursedcreationsteam.github.io/tree/new-codebase" .

**Comment by AlphaMode** [comment]
Ah, right that. I used to have relations with that group.

**Comment by AESisverystrong** [comment]
Well, I hope you'll post your new project on Github when you're done, so we can see the bigger world to show the **"infinite possibilities" of Minecraft**!
